# router swap identifier, must have prefix 'routerswap'
Identifier = "routerswap-test"
# router swap type (eg. erc20swap, nftswap, anycallswap)
SwapType = "erc20swap"
# default subtype is empty. anycall has subtype of 'curve'
SwapSubType = ""

# modgodb database connection config
[Server.MongoDB]
DBName = "testdb"
DBURLs = ["192.168.110.70:27017"]
Password = "123456"
UserName = "tester"

# bridge API service
[Server.APIServer]
# listen port
Port = 11556

# OnChain config
[OnChain]
APIAddress = ["https://rpc.testnet.fantom.network/"]
Contract = "0xBE04e6B86c7d5A14F83Bc8f57A6Eb68d4d974F64"

# Gateways config. key is chainID
[Gateways]
1645027868240 = ["http://localhost:3100/graphql"]
4002 = ["https://rpc.testnet.fantom.network/"]

# MPC config
[MPC]
# use private key instead (use for testing)
SignWithPrivateKey = true

# set signer's private key, key is chain ID (use for testing)
[MPC.SignerPrivateKeys]
1645027868240 = "6aead8d951a9872e73d25adc707de47d10354c90ad61e72177900d2b42e6fcb3"
4002 = "1380ad6b4394f646a868c8cfe17402c0e4d365b8ef0f1ecdfae4dd60a520f322"
