# router swap identifier, must have prefix 'routerswap'
Identifier = "routerswap-test"
# router swap type (eg. erc20swap, nftswap, anycallswap)
SwapType = "erc20swap"
# default subtype is empty. anycall has subtype of 'curve'
SwapSubType = ""

# modgodb database connection config
[Server.MongoDB]
DBName = "testdb"
DBURLs = ["192.168.110.70:27017"]
Password = "123456"
UserName = "tester"

# bridge API service
[Server.APIServer]
# listen port
Port = 11556

# OnChain config
[OnChain]
APIAddress = ["https://rinkeby.infura.io/v3/8e1493b73b104925b1d3b95abd3fd767"]
Contract = "0x4342F2b5224a43541BE7C8F39B92D7fEaA74d038"

# Gateways config. key is chainID
[Gateways]
1000005788241 = ["wss://s.altnet.rippletest.net:51233"]
4 = ["https://rinkeby.infura.io/v3/8e1493b73b104925b1d3b95abd3fd767"]

# MPC config
[MPC]
# use private key instead (use for testing)
SignWithPrivateKey = true

# set signer's private key, key is chain ID (use for testing)
[MPC.SignerPrivateKeys]
1000005788241 = "1111111111111111111111111111111111111111111111111111111111111111"
97 = "1111111111111111111111111111111111111111111111111111111111111111"
